encoding: utf-8

author: Brian M'Ikiara
title: Ikiara's Portfolio
description: >-
  😂 Hellough! Thanks for being here! Hope you like my Portfolio...Fingers
  crossed!
baseurl: "/"
url: "https://m-ikiara.github.io"
github_username:  m-ikiara
linkedin_username: m-ikiara
twitter_username: m_ikiara
disqus:
  shortname: 'https-brian-ikiara-github-io'

# Build settings
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
